-- ─────────────────────────────────────────────────────────────────────────────
-- Woodlands Attendance — HISTORICAL. Written as a "paste into the SQL
-- editor" script, not a numbered migration. Everything below is already
-- applied live.
--
-- 9 August 2026 migration-history reconciliation removed the parts of this
-- file that broke a from-files rebuild (`supabase db reset` runs seed.sql
-- after migrations):
--   - the bar_week_config RLS/policy block — that table was dropped by
--     018_drop_dead_tables.sql, so ENABLE ROW LEVEL SECURITY on it here
--     would fail against a fresh rebuild.
--   - the shift_settings RLS/policy block — shift_settings is now created,
--     with RLS and canonical policies, by 032_shift_settings.sql. This
--     file's copy used different (legacy) policy names and is now
--     redundant.
--   - the four clock_in_lat/lng, clock_out_lat/lng column adds — now owned
--     by 035_attendance_gps_columns.sql.
-- See WOODLANDS_FOLLOWUPS.md — POST-MEETING PRIORITY 1 for the full finding.
--
-- 10 August 2026, Session B (012 auth) removed the remainder of the
-- attendance DDL. This file is now free of attendance schema and policy
-- statements entirely:
--
--   - the attendance_records RLS + policy block. Its two policies
--     ("service role full access attendance_records" and the blanket
--     "authenticated read attendance_records", SELECT/authenticated/
--     USING(true)) are dropped live and replaced by the canonical set in
--     036_attendance_rls_reconcile.sql, which is now the single owner of RLS
--     on this table. Left here, this block would re-create both policies on
--     every `db reset` — seed.sql runs AFTER migrations — silently
--     reinstating the blanket read that 036 exists to remove.
--
--   - the user_id / shift_date / within_radius / break_start / break_end
--     column adds, which duplicated 010_attendance_user_id.sql. 010 now
--     carries the two DEFAULTs this file was the real source of
--     (shift_date DEFAULT CURRENT_DATE, within_radius DEFAULT false), so
--     nothing is lost by removing them here.
--
--   - `ALTER COLUMN staff_id DROP NOT NULL`, which duplicated 010.
--
--   - `ALTER COLUMN date DROP NOT NULL`. THIS ONE WAS NOT A DUPLICATE AND
--     NEVER TOOK EFFECT: live `attendance_records.date` is still NOT NULL
--     (verified 10 August 2026), matching 001_schema.sql:104 and no
--     migration relaxes it. Keeping the statement would have made a
--     from-files rebuild produce a NULLABLE `date` and diverge from
--     production on the §2.6 proof — the opposite of what this file's
--     presence implied. TodayTab.jsx:169 and :202 already document the
--     live NOT NULL and set `date` explicitly on every manager-path insert.
--
-- Still here, deliberately: the user_profiles shift_name / bar_week adds,
-- which duplicate 011_user_shift_fields.sql. Idempotent (IF NOT EXISTS),
-- already applied live, and not a rebuild landmine. Out of scope for an
-- attendance session; noted in WOODLANDS_FOLLOWUPS.md.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE user_profiles
  ADD COLUMN IF NOT EXISTS shift_name text,
  ADD COLUMN IF NOT EXISTS bar_week   text CHECK (bar_week IN ('A','B'));
