-- ============================================================
-- Woodlands stock reset + bar stock catalogue import
-- scripts/data-ops/002_bar_stock_reset_and_import.sql
-- Prepared 27 July 2026 (pre-meeting)
-- ============================================================
--
-- STATUS AT COMMIT: NOT YET APPLIED to the live database.
--   Live state when this file was written: 25 test stock_items,
--   25 current_stock rows, 0 stock_movements, 0 event_stock_allocations.
--
-- PRECONDITION:
--   Migration 030 must be applied FIRST. It widens the movement_type
--   CHECK to permit 'opening_balance'. The live CHECK (verified 27 July)
--   is still migration 008's four values — delivery / transfer /
--   adjustment / requisition — so STEP 3 WILL fail without 030.
--
-- ARCHITECTURE (verified against the live DB, 27 July 2026):
--   current_stock is a BASE TABLE (pg_class.relkind = 'r'), not a view.
--   There are NO triggers on stock_items, stock_movements or current_stock.
--   Nothing derives a balance from the movement ledger — StockLevelsTab
--   reads current_stock directly.
--   Therefore this script must write BOTH: the movement rows (audit trail)
--   and the current_stock rows (the balances the UI actually reads).
--   STEP 4 derives current_stock from the movements so the two cannot
--   disagree by construction.
--
-- Rationale:
--   Real bar stock LEVELS were not received — the source files are a
--   mid-cycle snapshot with mostly zero opening balances. We import the
--   real item catalogue with deterministic realistic demo quantities.
--   Framing: 'the items are real; the quantities are placeholder — we
--   need your stocktake to load actual levels.'
--
--   All other stock departments (Housekeeping, Kitchen, Grounds,
--   Restaurant, Security) are wiped. Framing: 'we only have bar stock
--   right now, waiting on your lists for the other departments.'
--
-- What lands:
--   276 Restaurant Bar + 283 Sports Bar = 559 stock_items
--   Units: 84 crates, 475 bottles
--   533 opening_balance movement rows (26 items open at zero, so get none)
--   559 current_stock rows — every item, including the 26 zeros
--   Distribution: 26 out-of-stock, 78 below reorder, 455 at/above reorder
--   Selling prices: not imported (inventory tracking, not accounting)
--
-- One-shot. NOT to be replayed on rebuild.

BEGIN;

-- ============================================================
-- STEP 0 — Guard: refuse to run if event stock allocations exist
-- ============================================================
--
-- event_stock_allocations FKs to stock_items with ON DELETE RESTRICT and
-- is deliberately NOT deleted here — those rows belong to events, and
-- wiping them to clear the way for a stock import would destroy event
-- data. If any exist, stop with a clear message rather than an opaque
-- FK violation.

DO $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM event_stock_allocations;
  IF n > 0 THEN
    RAISE EXCEPTION
      'event_stock_allocations holds % row(s). stock_items cannot be deleted while these exist (FK is ON DELETE RESTRICT). Resolve the affected events before running this import.', n;
  END IF;
END $$;

-- ============================================================
-- STEP 1 — Wipe existing stock data (test rows only)
-- ============================================================
--
-- FK dependency order: children before parent. current_stock,
-- requisitions and stock_movements are all ON DELETE CASCADE from
-- stock_items, so the explicit deletes are belt-and-braces.

DELETE FROM stock_movements;
DELETE FROM requisitions;
DELETE FROM current_stock;
DELETE FROM stock_items;

-- Verify empty before insert:
--   SELECT (SELECT count(*) FROM stock_items)     AS items,
--          (SELECT count(*) FROM current_stock)   AS cur_stock,
--          (SELECT count(*) FROM stock_movements) AS movements,
--          (SELECT count(*) FROM requisitions)    AS reqs;
--   -- all four should be 0

-- ============================================================
-- STEP 2 — Insert 559 real bar stock items (catalogue only)
-- ============================================================

INSERT INTO stock_items (sku, name, department, unit, reorder_level) VALUES
  ('RBA-980', 'COURVOISIER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-976', 'FIVES RESERVE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-978', 'HENNESSY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-41', 'KLIPDRIFT PREMIUM', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1571', 'KWV 5 YRS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-43', 'KWV BRANDY (10YR)', 'Restaurant Bar', 'bottles', 5),
  ('RBA-44', 'KWV BRANDY (3YR)', 'Restaurant Bar', 'bottles', 5),
  ('RBA-989', 'MARTELL - COGNAC', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1422', 'PREMIER BRANDY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-981', 'VETERANO', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1722', 'VICEROY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1197', 'DROSTDY HOF RED', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1196', 'DROSTDY HOF WHITE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1112', 'JOHANISBURG RED WINE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1195', 'JOHANISBURGER WHITE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1420', 'OVERMILLER DRY WHITE WINE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1421', 'OVERMILLER STEIN', 'Restaurant Bar', 'bottles', 5),
  ('RBA-649', 'RED DRY WINE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-108', 'ROBERTSON', 'Restaurant Bar', 'bottles', 5),
  ('RBA-107', 'ROSE JOHANNESBURGER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-561', 'AMSTEL', 'Restaurant Bar', 'crates', 8),
  ('RBA-1710', 'BONE CRUSHER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1001', 'BREEZER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1695', 'BRUTAL FRUIT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1006', 'BUDWIER', 'Restaurant Bar', 'crates', 8),
  ('RBA-804', 'CARIBBEAN TWIST', 'Restaurant Bar', 'bottles', 5),
  ('RBA-656', 'CARLING BLACK LABEL', 'Restaurant Bar', 'crates', 8),
  ('RBA-1291', 'CASTLE LAGER', 'Restaurant Bar', 'crates', 8),
  ('RBA-54', 'CASTLE LIGHT', 'Restaurant Bar', 'crates', 8),
  ('RBA-86', 'CASTLE MILK STOUT', 'Restaurant Bar', 'crates', 8),
  ('RBA-805', 'CORONA EXTRA', 'Restaurant Bar', 'crates', 8),
  ('RBA-1264', 'FLYING FISH', 'Restaurant Bar', 'bottles', 5),
  ('RBA-751', 'GUINESS BEER - CAN', 'Restaurant Bar', 'crates', 8),
  ('RBA-47', 'HEINEKEN', 'Restaurant Bar', 'crates', 8),
  ('RBA-1351', 'HOEGAARDEN', 'Restaurant Bar', 'bottles', 5),
  ('RBA-81', 'HUNTERS DRY', 'Restaurant Bar', 'crates', 8),
  ('RBA-82', 'HUNTERS GOLD', 'Restaurant Bar', 'crates', 8),
  ('RBA-1713', 'JUST BEER', 'Restaurant Bar', 'crates', 8),
  ('RBA-53', 'MILLER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1711', 'ROGUE PONY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-80', 'SAVANNA', 'Restaurant Bar', 'crates', 8),
  ('RBA-1712', 'SLOW BEER', 'Restaurant Bar', 'crates', 8),
  ('RBA-84', 'SMIRNOFF SPIN', 'Restaurant Bar', 'bottles', 5),
  ('RBA-83', 'SMIRNOFF STORM', 'Restaurant Bar', 'bottles', 5),
  ('RBA-806', 'STELLA ARTOIS', 'Restaurant Bar', 'crates', 8),
  ('RBA-752', 'WINDHOCK LIGHT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1032', 'WINDHOEK DRAUGHT', 'Restaurant Bar', 'crates', 8),
  ('RBA-567', 'WINDHOEK LAGER', 'Restaurant Bar', 'crates', 8),
  ('RBA-1718', 'WINDHOEK LAGER LARGE', 'Restaurant Bar', 'crates', 8),
  ('RBA-495', 'DUNHILL BLUE.', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1551', 'DUNHILL RED', 'Restaurant Bar', 'bottles', 5),
  ('RBA-112', 'PALL MALL KINGS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-113', 'PALL MALL MENTHOL', 'Restaurant Bar', 'bottles', 5),
  ('RBA-111', 'PETERS STUYVESANT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1318', 'BOMBAY SAPPHIRE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1319', 'CAPETOWN GIN', 'Restaurant Bar', 'bottles', 5),
  ('RBA-45', 'GORDONS DRY GIN', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1314', 'GUNPOWDER GIN', 'Restaurant Bar', 'bottles', 5),
  ('RBA-46', 'MALAWI GIN', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1725', 'TANQUERAY GIN', 'Restaurant Bar', 'bottles', 5),
  ('RBA-519', 'APPLE JUICE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-733', 'CRANBERRY JUICE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1317', 'GINGER BEER', 'Restaurant Bar', 'crates', 8),
  ('RBA-425', 'GUAVA JUICE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-665', 'JUICE 1LT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-426', 'LITCH JUICE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-520', 'MANGO JUICE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-423', 'ORANGE JUICE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1024', 'ORANGE SQUASH 35 ML', 'Restaurant Bar', 'bottles', 5),
  ('RBA-497', 'PINEAPPLE JUICE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1016', 'RED GRAPE JUICE 250 ML', 'Restaurant Bar', 'bottles', 5),
  ('RBA-424', 'TROPICAL JUICE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1022', 'AMARULA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-979', 'AMARULA GOLD', 'Restaurant Bar', 'bottles', 5),
  ('RBA-664', 'BAILEYS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-963', 'BERTRAMS - SHERRY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-514', 'BLUE CARCAO', 'Restaurant Bar', 'bottles', 5),
  ('RBA-973', 'CAMPARI', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1185', 'CINZANO BIANCO', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1159', 'DEKUYPER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1322', 'DISARONNO', 'Restaurant Bar', 'bottles', 5),
  ('RBA-67', 'DRAMBIE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-961', 'GRAN POMIER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-65', 'KAHLUA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1610', 'KWV SHERRY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-970', 'LINI AQUAVIT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-969', 'LUPINI - SAMBUCA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-957', 'MARTINI - BIANCO', 'Restaurant Bar', 'bottles', 5),
  ('RBA-64', 'MARTINI EXTRA DRY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-977', 'OUZO', 'Restaurant Bar', 'bottles', 5),
  ('RBA-513', 'PEPPERMINT LIQUER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-966', 'PIMMS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-63', 'RED CINZANO (ROSSO)', 'Restaurant Bar', 'bottles', 5),
  ('RBA-68', 'SAMBUCA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1662', 'STRAWBERRY LIPS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-611', 'TIA MARIA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-959', 'VACCARI - SAMBUCA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-968', 'WILD AFRICA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-975', 'YENI RAKI', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1168', 'CASTEL BEER', 'Restaurant Bar', 'crates', 8),
  ('RBA-11', 'CHILL', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1469', 'DOPPEL MUNICH', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1698', 'DUSTY HAZE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1709', 'EARTHY ENGLISH', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1454', 'GREEN', 'Restaurant Bar', 'crates', 8),
  ('RBA-1109', 'KUCHE KUCHE', 'Restaurant Bar', 'crates', 8),
  ('RBA-1714', 'LAKESIDE LAGER', 'Restaurant Bar', 'crates', 8),
  ('RBA-1697', 'PAVED PILSNER', 'Restaurant Bar', 'crates', 8),
  ('RBA-1706', 'POMME BREEZE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1720', 'PORTHOLE PALE', 'Restaurant Bar', 'crates', 8),
  ('RBA-1699', 'RUMBLE RED', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1731', 'SAPITWA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1700', 'SHORTCUT STOUT', 'Restaurant Bar', 'crates', 8),
  ('RBA-3', 'SPECIAL BREW', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1432', '7 UP', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1433', '1 LITER WATER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-19', 'APPETISER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-13', 'CHERRY PLUM', 'Restaurant Bar', 'bottles', 5),
  ('RBA-370', 'COCOPINA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-608', 'COKE', 'Restaurant Bar', 'crates', 8),
  ('RBA-1425', 'COKE - TIN', 'Restaurant Bar', 'crates', 8),
  ('RBA-7', 'COKE LIGHT', 'Restaurant Bar', 'crates', 8),
  ('RBA-494', 'FANTA ORANGE.', 'Restaurant Bar', 'crates', 8),
  ('RBA-1726', 'FANTA PASSION', 'Restaurant Bar', 'crates', 8),
  ('RBA-280', 'FANTA PINEAPPLE', 'Restaurant Bar', 'crates', 8),
  ('RBA-1009', 'GINGER ALE BOTTEL', 'Restaurant Bar', 'crates', 8),
  ('RBA-1025', 'GINGER ALE TIN', 'Restaurant Bar', 'crates', 8),
  ('RBA-722', 'GLASS OF COKE LIGHT', 'Restaurant Bar', 'crates', 8),
  ('RBA-18', 'GRAPETISER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-937', 'ICED TEA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-20', 'LIME CORDIAL', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1029', 'PEPSI LIGHT', 'Restaurant Bar', 'crates', 8),
  ('RBA-23', 'RED BULL', 'Restaurant Bar', 'bottles', 5),
  ('RBA-25', 'SODA WATER TIN', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1217', 'SPARKLING WATER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1097', 'SPARKLING WATER LARGE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1460', 'SPRITE', 'Restaurant Bar', 'crates', 8),
  ('RBA-434', 'TONIC CAN', 'Restaurant Bar', 'bottles', 5),
  ('RBA-17', 'WATER 500ML', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1044', 'BITTERS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1648', 'BROOKDALE ROSE', 'Restaurant Bar', 'crates', 8),
  ('RBA-1293', 'CAPPUCHINO CUBES', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1355', 'FRENCH CHAMPAGNE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1142', 'GRACA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1627', 'HOT CHOCOLATE.', 'Restaurant Bar', 'bottles', 5),
  ('RBA-823', 'JC LEROUX', 'Restaurant Bar', 'bottles', 5),
  ('RBA-544', 'LINGA WINE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1220', 'NED ROSE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1147', 'NOBLE SWEET ROSE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1447', 'PLASTIC GLASS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1657', 'PROTEA PINOT GRIGION', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1647', 'PROTEA ROSE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1658', 'SPIER SECRET SPARKLING ROSE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1642', 'BENGUELA COVE SYRAH', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1289', 'BOCHANDAL MERLOT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1104', 'BOSCHANDAL-CABERNET SAVUGNON', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1108', 'BOSCHANDAL-SHIRAZ', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1643', 'BROOKDALE SYRAH', 'Restaurant Bar', 'crates', 8),
  ('RBA-1613', 'BRUNELLO MALBEC', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1437', 'BRUNELLO- MERLOT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1636', 'CEDERBERG CAB SAV', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1354', 'DURBAN VALLY HILLS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1107', 'FLEUR DU CAP-CABERNET SAVUGNON', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1106', 'FLEUR DU CAP-SHIRAZ', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1170', 'FLUER DU CAP - MERLOT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1427', 'FOUR COUSIN SWEET RED', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1635', 'HERTENBURG BLEND', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1729', 'KEN FORESTER CARBINET SAV', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1641', 'KEN FORRESTER PINOTAGE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1645', 'MITRES EDGE MALBEC', 'Restaurant Bar', 'bottles', 5),
  ('RBA-99', 'NED BARONNE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-737', 'NED MERLOT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1099', 'NED PINOTAGE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-583', 'NEDERBERG DUET', 'Restaurant Bar', 'bottles', 5),
  ('RBA-730', 'NEDERBURG SHIRAZ', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1644', 'NEETHLINGSHOF MALBEC', 'Restaurant Bar', 'bottles', 5),
  ('RBA-102', 'NEGERBURG CABERNET SAUV.', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1143', 'NOBLE DRY RED', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1144', 'NOBLE SWEET RED', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1646', 'OLDENBURG CL', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1640', 'PAINTED WOLF SHIRAZ', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1611', 'PARMOUNT SYRAH', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1638', 'PROTEA MERLOT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1639', 'REMHOOGTE MERLOT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1660', 'REMHOOGTE PINOTAGE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1637', 'SPIER MERLOT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1659', 'TOKARA CAB SAV', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1612', 'ZONNEBLOEM CAB SAV', 'Restaurant Bar', 'bottles', 5),
  ('RBA-501', 'ZONNEBLOM MERLOT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-651', 'ZONNEBLOM PINOTAGE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-504', 'ZONNEBLOM SHIRAZ', 'Restaurant Bar', 'bottles', 5),
  ('RBA-59', 'BACARDI', 'Restaurant Bar', 'bottles', 5),
  ('RBA-56', 'CAPTAIN MORGAN BALCK', 'Restaurant Bar', 'bottles', 5),
  ('RBA-57', 'CAPTAIN MORGAN SPICED', 'Restaurant Bar', 'bottles', 5),
  ('RBA-972', 'CARIBBEAN WHITE RUM', 'Restaurant Bar', 'bottles', 5),
  ('RBA-971', 'HAVANA CLUB', 'Restaurant Bar', 'bottles', 5),
  ('RBA-60', 'MALAWI RUM', 'Restaurant Bar', 'bottles', 5),
  ('RBA-70', 'MARIBU', 'Restaurant Bar', 'bottles', 5),
  ('RBA-76', 'INFERNO LUPINI', 'Restaurant Bar', 'bottles', 5),
  ('RBA-78', 'JAGERMEISTER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-79', 'OLMECA TEQUILA RED', 'Restaurant Bar', 'bottles', 5),
  ('RBA-75', 'OLMECA TEQUILA WHITE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-74', 'ZAPPA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-822', 'FOUR COUSIN- ROSE WINE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-29', 'ABSOLUTE VODKA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1569', 'C ROCK VODKA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1723', 'CRUZ VODKA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1568', 'GREY GOOSE VODKA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-30', 'MAINSTAY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-27', 'MALAWI VODKA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1570', 'SKY VODKA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-28', 'SMIRNOFF VODKA', 'Restaurant Bar', 'bottles', 5),
  ('RBA-967', 'BALLENTIES', 'Restaurant Bar', 'bottles', 5),
  ('RBA-986', 'BALLENTIES 12 YEARS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-33', 'BELLS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-31', 'BLACK LABEL', 'Restaurant Bar', 'crates', 8),
  ('RBA-987', 'CHINEESE WHISKY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1667', 'CHINESE WHISKY BOTTLE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-32', 'CHIVAS REGAL', 'Restaurant Bar', 'bottles', 5),
  ('RBA-816', 'DOUBLE BLACK LABLE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-954', 'FAMOUSE GROUSE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1297', 'GLENFARCLAS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1441', 'GLENFIDDICH 15 YEARS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1462', 'GLENFIDDICH 18 YEARS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-34', 'GLENFIDDISH 12 YEARS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-988', 'GLENGARIOCH', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1566', 'GLENLIVET 12YRS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1567', 'GLENLIVET FOUNDERS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-950', 'GLENMORANGIE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-965', 'GLENROTHERS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1190', 'GOLD LABEL JOHNIW WALKER', 'Restaurant Bar', 'bottles', 5),
  ('RBA-815', 'GRANTS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1565', 'GREEN LABEL', 'Restaurant Bar', 'crates', 8),
  ('RBA-990', 'GUIZHOU MOUNTAIN ZHEN', 'Restaurant Bar', 'bottles', 5),
  ('RBA-35', 'J & B', 'Restaurant Bar', 'bottles', 5),
  ('RBA-724', 'JACK DANIEL HONEY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1027', 'JACK DANIELS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1461', 'JAMESON', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1271', 'JAMESON - SELECT RESERVE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1005', 'JIM BEAM', 'Restaurant Bar', 'bottles', 5),
  ('RBA-982', 'JOHNEEWALKER ADVENTURE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-991', 'KWEICHOW MOUTAI', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1575', 'MACALLAN 12 YEARS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-958', 'PASSPORT- SCOTCH', 'Restaurant Bar', 'bottles', 5),
  ('RBA-985', 'RAGGANMORE 12 YEARS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-36', 'RED LABEL', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1724', 'SINGLETONE WHISKY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-72', 'SOUTHERN COMFORT', 'Restaurant Bar', 'bottles', 5),
  ('RBA-964', 'WOODFORD RESERVE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1655', 'BEUMONT CHENIN BLANK', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1035', 'BOSCHANDAL-CHARDONAY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1105', 'BOSCHANDAL-SAVUGNON BLANC', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1661', 'CAPE OF GOOD HOPE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1656', 'CEBERBERG GHOST CORNER SEMILLION', 'Restaurant Bar', 'crates', 8),
  ('RBA-1140', 'CHIANTI', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1110', 'FLEUR DU CAP-CHARDONAY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1103', 'FLEUR DU CAP-SAVUGNON BLANC', 'Restaurant Bar', 'bottles', 5),
  ('RBA-775', 'FOUR COUSIN - SWEET WHITE WINE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1651', 'HARTENBERG CHARDONNAY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1650', 'KEN FORRESTER CHARDONNAY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1654', 'KEN FORRESTER CHENIN BLANC', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1653', 'KEN FORRESTER SAV BLANC', 'Restaurant Bar', 'bottles', 5),
  ('RBA-91', 'NED LYRIC', 'Restaurant Bar', 'bottles', 5),
  ('RBA-93', 'NED SAUV. BLANC', 'Restaurant Bar', 'bottles', 5),
  ('RBA-682', 'NEDBERG RIESLING', 'Restaurant Bar', 'bottles', 5),
  ('RBA-511', 'NEDER STEINS', 'Restaurant Bar', 'bottles', 5),
  ('RBA-913', 'NEDERBURG - CHARDONAY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1145', 'NOBLE DRY WHITE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1146', 'NOBLE SWEET WHITE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1042', 'PINOT GRIGIO', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1141', 'PROSECCO', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1649', 'SPIER CHARDONNAY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1728', 'SPIER ROSE', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1652', 'SPIER SAV BLANK', 'Restaurant Bar', 'bottles', 5),
  ('RBA-1004', 'ZONNEBLOM CHARDONAY', 'Restaurant Bar', 'bottles', 5),
  ('RBA-634', 'ZONNEBLOMBLOEM SAUVIGNO BLANC', 'Restaurant Bar', 'bottles', 5),
  ('SBA-980', 'COURVOISIER', 'Sports Bar', 'bottles', 5),
  ('SBA-976', 'FIVES RESERVE', 'Sports Bar', 'bottles', 5),
  ('SBA-978', 'HENNESSY', 'Sports Bar', 'bottles', 5),
  ('SBA-41', 'KLIPDRIFT PREMIUM', 'Sports Bar', 'bottles', 5),
  ('SBA-1571', 'KWV 5 YRS', 'Sports Bar', 'bottles', 5),
  ('SBA-43', 'KWV BRANDY (10YR)', 'Sports Bar', 'bottles', 5),
  ('SBA-44', 'KWV BRANDY (3YR)', 'Sports Bar', 'bottles', 5),
  ('SBA-989', 'MARTELL - COGNAC', 'Sports Bar', 'bottles', 5),
  ('SBA-1422', 'PREMIER BRANDY', 'Sports Bar', 'bottles', 5),
  ('SBA-981', 'VETERANO', 'Sports Bar', 'bottles', 5),
  ('SBA-1722', 'VICEROY', 'Sports Bar', 'bottles', 5),
  ('SBA-1197', 'DROSTDY HOF RED', 'Sports Bar', 'bottles', 5),
  ('SBA-1196', 'DROSTDY HOF WHITE', 'Sports Bar', 'bottles', 5),
  ('SBA-1112', 'JOHANISBURG RED WINE', 'Sports Bar', 'bottles', 5),
  ('SBA-1195', 'JOHANISBURGER WHITE', 'Sports Bar', 'bottles', 5),
  ('SBA-1420', 'OVERMILLER DRY WHITE WINE', 'Sports Bar', 'bottles', 5),
  ('SBA-1421', 'OVERMILLER STEIN', 'Sports Bar', 'bottles', 5),
  ('SBA-649', 'RED DRY WINE', 'Sports Bar', 'bottles', 5),
  ('SBA-108', 'ROBERTSON', 'Sports Bar', 'bottles', 5),
  ('SBA-107', 'ROSE JOHANNESBURGER', 'Sports Bar', 'bottles', 5),
  ('SBA-561', 'AMSTEL', 'Sports Bar', 'crates', 8),
  ('SBA-1710', 'BONE CRUSHER', 'Sports Bar', 'bottles', 5),
  ('SBA-1001', 'BREEZER', 'Sports Bar', 'bottles', 5),
  ('SBA-1695', 'BRUTAL FRUIT', 'Sports Bar', 'bottles', 5),
  ('SBA-1006', 'BUDWIER', 'Sports Bar', 'crates', 8),
  ('SBA-804', 'CARIBBEAN TWIST', 'Sports Bar', 'bottles', 5),
  ('SBA-656', 'CARLING BLACK LABEL', 'Sports Bar', 'crates', 8),
  ('SBA-1291', 'CASTLE LAGER', 'Sports Bar', 'crates', 8),
  ('SBA-54', 'CASTLE LIGHT', 'Sports Bar', 'crates', 8),
  ('SBA-86', 'CASTLE MILK STOUT', 'Sports Bar', 'crates', 8),
  ('SBA-805', 'CORONA EXTRA', 'Sports Bar', 'crates', 8),
  ('SBA-1264', 'FLYING FISH', 'Sports Bar', 'bottles', 5),
  ('SBA-751', 'GUINESS BEER - CAN', 'Sports Bar', 'crates', 8),
  ('SBA-47', 'HEINEKEN', 'Sports Bar', 'crates', 8),
  ('SBA-1351', 'HOEGAARDEN', 'Sports Bar', 'bottles', 5),
  ('SBA-81', 'HUNTERS DRY', 'Sports Bar', 'crates', 8),
  ('SBA-82', 'HUNTERS GOLD', 'Sports Bar', 'crates', 8),
  ('SBA-1713', 'JUST BEER', 'Sports Bar', 'crates', 8),
  ('SBA-53', 'MILLER', 'Sports Bar', 'bottles', 5),
  ('SBA-1711', 'ROGUE PONY', 'Sports Bar', 'bottles', 5),
  ('SBA-80', 'SAVANNA', 'Sports Bar', 'crates', 8),
  ('SBA-1712', 'SLOW BEER', 'Sports Bar', 'crates', 8),
  ('SBA-84', 'SMIRNOFF SPIN', 'Sports Bar', 'bottles', 5),
  ('SBA-83', 'SMIRNOFF STORM', 'Sports Bar', 'bottles', 5),
  ('SBA-806', 'STELLA ARTOIS', 'Sports Bar', 'crates', 8),
  ('SBA-752', 'WINDHOCK LIGHT', 'Sports Bar', 'bottles', 5),
  ('SBA-1032', 'WINDHOEK DRAUGHT', 'Sports Bar', 'crates', 8),
  ('SBA-567', 'WINDHOEK LAGER', 'Sports Bar', 'crates', 8),
  ('SBA-1718', 'WINDHOEK LAGER LARGE', 'Sports Bar', 'crates', 8),
  ('SBA-495', 'DUNHILL BLUE.', 'Sports Bar', 'bottles', 5),
  ('SBA-1551', 'DUNHILL RED', 'Sports Bar', 'bottles', 5),
  ('SBA-112', 'PALL MALL KINGS', 'Sports Bar', 'bottles', 5),
  ('SBA-113', 'PALL MALL MENTHOL', 'Sports Bar', 'bottles', 5),
  ('SBA-111', 'PETERS STUYVESANT', 'Sports Bar', 'bottles', 5),
  ('SBA-1318', 'BOMBAY SAPPHIRE', 'Sports Bar', 'bottles', 5),
  ('SBA-1743', 'BULL DOG GIN', 'Sports Bar', 'bottles', 5),
  ('SBA-1319', 'CAPETOWN GIN', 'Sports Bar', 'bottles', 5),
  ('SBA-45', 'GORDONS DRY GIN', 'Sports Bar', 'bottles', 5),
  ('SBA-1314', 'GUNPOWDER GIN', 'Sports Bar', 'bottles', 5),
  ('SBA-1742', 'HENDRICKS GIN', 'Sports Bar', 'bottles', 5),
  ('SBA-46', 'MALAWI GIN', 'Sports Bar', 'bottles', 5),
  ('SBA-1725', 'TANQUERAY GIN', 'Sports Bar', 'bottles', 5),
  ('SBA-519', 'APPLE JUICE', 'Sports Bar', 'bottles', 5),
  ('SBA-733', 'CRANBERRY JUICE', 'Sports Bar', 'bottles', 5),
  ('SBA-1317', 'GINGER BEER', 'Sports Bar', 'crates', 8),
  ('SBA-425', 'GUAVA JUICE', 'Sports Bar', 'bottles', 5),
  ('SBA-665', 'JUICE 1LT', 'Sports Bar', 'bottles', 5),
  ('SBA-426', 'LITCH JUICE', 'Sports Bar', 'bottles', 5),
  ('SBA-520', 'MANGO JUICE', 'Sports Bar', 'bottles', 5),
  ('SBA-423', 'ORANGE JUICE', 'Sports Bar', 'bottles', 5),
  ('SBA-1024', 'ORANGE SQUASH 35 ML', 'Sports Bar', 'bottles', 5),
  ('SBA-497', 'PINEAPPLE JUICE', 'Sports Bar', 'bottles', 5),
  ('SBA-1016', 'RED GRAPE JUICE 250 ML', 'Sports Bar', 'bottles', 5),
  ('SBA-424', 'TROPICAL JUICE', 'Sports Bar', 'bottles', 5),
  ('SBA-1022', 'AMARULA', 'Sports Bar', 'bottles', 5),
  ('SBA-979', 'AMARULA GOLD', 'Sports Bar', 'bottles', 5),
  ('SBA-1741', 'APEROL', 'Sports Bar', 'bottles', 5),
  ('SBA-664', 'BAILEYS', 'Sports Bar', 'bottles', 5),
  ('SBA-963', 'BERTRAMS - SHERRY', 'Sports Bar', 'bottles', 5),
  ('SBA-514', 'BLUE CARCAO', 'Sports Bar', 'bottles', 5),
  ('SBA-973', 'CAMPARI', 'Sports Bar', 'bottles', 5),
  ('SBA-1185', 'CINZANO BIANCO', 'Sports Bar', 'bottles', 5),
  ('SBA-1159', 'DEKUYPER', 'Sports Bar', 'bottles', 5),
  ('SBA-1322', 'DISARONNO', 'Sports Bar', 'bottles', 5),
  ('SBA-67', 'DRAMBIE', 'Sports Bar', 'bottles', 5),
  ('SBA-961', 'GRAN POMIER', 'Sports Bar', 'bottles', 5),
  ('SBA-65', 'KAHLUA', 'Sports Bar', 'bottles', 5),
  ('SBA-1610', 'KWV SHERRY', 'Sports Bar', 'bottles', 5),
  ('SBA-970', 'LINI AQUAVIT', 'Sports Bar', 'bottles', 5),
  ('SBA-969', 'LUPINI - SAMBUCA', 'Sports Bar', 'bottles', 5),
  ('SBA-957', 'MARTINI - BIANCO', 'Sports Bar', 'bottles', 5),
  ('SBA-64', 'MARTINI EXTRA DRY', 'Sports Bar', 'bottles', 5),
  ('SBA-977', 'OUZO', 'Sports Bar', 'bottles', 5),
  ('SBA-513', 'PEPPERMINT LIQUER', 'Sports Bar', 'bottles', 5),
  ('SBA-966', 'PIMMS', 'Sports Bar', 'bottles', 5),
  ('SBA-63', 'RED CINZANO (ROSSO)', 'Sports Bar', 'bottles', 5),
  ('SBA-68', 'SAMBUCA', 'Sports Bar', 'bottles', 5),
  ('SBA-1662', 'STRAWBERRY LIPS', 'Sports Bar', 'bottles', 5),
  ('SBA-611', 'TIA MARIA', 'Sports Bar', 'bottles', 5),
  ('SBA-959', 'VACCARI - SAMBUCA', 'Sports Bar', 'bottles', 5),
  ('SBA-968', 'WILD AFRICA', 'Sports Bar', 'bottles', 5),
  ('SBA-975', 'YENI RAKI', 'Sports Bar', 'bottles', 5),
  ('SBA-1168', 'CASTEL BEER', 'Sports Bar', 'crates', 8),
  ('SBA-11', 'CHILL', 'Sports Bar', 'bottles', 5),
  ('SBA-1469', 'DOPPEL MUNICH', 'Sports Bar', 'bottles', 5),
  ('SBA-1698', 'DUSTY HAZE', 'Sports Bar', 'bottles', 5),
  ('SBA-1709', 'EARTHY ENGLISH', 'Sports Bar', 'bottles', 5),
  ('SBA-1454', 'GREEN', 'Sports Bar', 'crates', 8),
  ('SBA-1109', 'KUCHE KUCHE', 'Sports Bar', 'crates', 8),
  ('SBA-1714', 'LAKESIDE LAGER', 'Sports Bar', 'crates', 8),
  ('SBA-1697', 'PAVED PILSNER', 'Sports Bar', 'crates', 8),
  ('SBA-1706', 'POMME BREEZE', 'Sports Bar', 'bottles', 5),
  ('SBA-1720', 'PORTHOLE PALE', 'Sports Bar', 'crates', 8),
  ('SBA-1699', 'RUMBLE RED', 'Sports Bar', 'bottles', 5),
  ('SBA-1731', 'SAPITWA', 'Sports Bar', 'bottles', 5),
  ('SBA-1700', 'SHORTCUT STOUT', 'Sports Bar', 'crates', 8),
  ('SBA-3', 'SPECIAL BREW', 'Sports Bar', 'bottles', 5),
  ('SBA-1432', '7 UP', 'Sports Bar', 'bottles', 5),
  ('SBA-1433', '1 LITER WATER', 'Sports Bar', 'bottles', 5),
  ('SBA-19', 'APPETISER', 'Sports Bar', 'bottles', 5),
  ('SBA-13', 'CHERRY PLUM', 'Sports Bar', 'bottles', 5),
  ('SBA-370', 'COCOPINA', 'Sports Bar', 'bottles', 5),
  ('SBA-608', 'COKE', 'Sports Bar', 'crates', 8),
  ('SBA-1425', 'COKE - TIN', 'Sports Bar', 'crates', 8),
  ('SBA-7', 'COKE LIGHT', 'Sports Bar', 'crates', 8),
  ('SBA-494', 'FANTA ORANGE.', 'Sports Bar', 'crates', 8),
  ('SBA-1726', 'FANTA PASSION', 'Sports Bar', 'crates', 8),
  ('SBA-280', 'FANTA PINEAPPLE', 'Sports Bar', 'crates', 8),
  ('SBA-1009', 'GINGER ALE BOTTEL', 'Sports Bar', 'crates', 8),
  ('SBA-1025', 'GINGER ALE TIN', 'Sports Bar', 'crates', 8),
  ('SBA-722', 'GLASS OF COKE LIGHT', 'Sports Bar', 'crates', 8),
  ('SBA-18', 'GRAPETISER', 'Sports Bar', 'bottles', 5),
  ('SBA-937', 'ICED TEA', 'Sports Bar', 'bottles', 5),
  ('SBA-20', 'LIME CORDIAL', 'Sports Bar', 'bottles', 5),
  ('SBA-1029', 'PEPSI LIGHT', 'Sports Bar', 'crates', 8),
  ('SBA-23', 'RED BULL', 'Sports Bar', 'bottles', 5),
  ('SBA-25', 'SODA WATER TIN', 'Sports Bar', 'bottles', 5),
  ('SBA-1217', 'SPARKLING WATER', 'Sports Bar', 'bottles', 5),
  ('SBA-1097', 'SPARKLING WATER LARGE', 'Sports Bar', 'bottles', 5),
  ('SBA-1460', 'SPRITE', 'Sports Bar', 'crates', 8),
  ('SBA-434', 'TONIC CAN', 'Sports Bar', 'bottles', 5),
  ('SBA-17', 'WATER 500ML', 'Sports Bar', 'bottles', 5),
  ('SBA-1044', 'BITTERS', 'Sports Bar', 'bottles', 5),
  ('SBA-1648', 'BROOKDALE ROSE', 'Sports Bar', 'crates', 8),
  ('SBA-1293', 'CAPPUCHINO CUBES', 'Sports Bar', 'bottles', 5),
  ('SBA-1355', 'FRENCH CHAMPAGNE', 'Sports Bar', 'bottles', 5),
  ('SBA-1142', 'GRACA', 'Sports Bar', 'bottles', 5),
  ('SBA-1627', 'HOT CHOCOLATE.', 'Sports Bar', 'bottles', 5),
  ('SBA-823', 'JC LEROUX', 'Sports Bar', 'bottles', 5),
  ('SBA-544', 'LINGA WINE', 'Sports Bar', 'bottles', 5),
  ('SBA-1220', 'NED ROSE', 'Sports Bar', 'bottles', 5),
  ('SBA-1147', 'NOBLE SWEET ROSE', 'Sports Bar', 'bottles', 5),
  ('SBA-1447', 'PLASTIC GLASS', 'Sports Bar', 'bottles', 5),
  ('SBA-1657', 'PROTEA PINOT GRIGION', 'Sports Bar', 'bottles', 5),
  ('SBA-1647', 'PROTEA ROSE', 'Sports Bar', 'bottles', 5),
  ('SBA-1658', 'SPIER SECRET SPARKLING ROSE', 'Sports Bar', 'bottles', 5),
  ('SBA-1642', 'BENGUELA COVE SYRAH', 'Sports Bar', 'bottles', 5),
  ('SBA-1289', 'BOCHANDAL MERLOT', 'Sports Bar', 'bottles', 5),
  ('SBA-1104', 'BOSCHANDAL-CABERNET SAVUGNON', 'Sports Bar', 'bottles', 5),
  ('SBA-1108', 'BOSCHANDAL-SHIRAZ', 'Sports Bar', 'bottles', 5),
  ('SBA-1643', 'BROOKDALE SYRAH', 'Sports Bar', 'crates', 8),
  ('SBA-1613', 'BRUNELLO MALBEC', 'Sports Bar', 'bottles', 5),
  ('SBA-1437', 'BRUNELLO- MERLOT', 'Sports Bar', 'bottles', 5),
  ('SBA-1636', 'CEDERBERG CAB SAV', 'Sports Bar', 'bottles', 5),
  ('SBA-1354', 'DURBAN VALLY HILLS', 'Sports Bar', 'bottles', 5),
  ('SBA-1107', 'FLEUR DU CAP-CABERNET SAVUGNON', 'Sports Bar', 'bottles', 5),
  ('SBA-1106', 'FLEUR DU CAP-SHIRAZ', 'Sports Bar', 'bottles', 5),
  ('SBA-1170', 'FLUER DU CAP - MERLOT', 'Sports Bar', 'bottles', 5),
  ('SBA-1427', 'FOUR COUSIN SWEET RED', 'Sports Bar', 'bottles', 5),
  ('SBA-1635', 'HERTENBURG BLEND', 'Sports Bar', 'bottles', 5),
  ('SBA-1729', 'KEN FORESTER CARBINET SAV', 'Sports Bar', 'bottles', 5),
  ('SBA-1641', 'KEN FORRESTER PINOTAGE', 'Sports Bar', 'bottles', 5),
  ('SBA-1645', 'MITRES EDGE MALBEC', 'Sports Bar', 'bottles', 5),
  ('SBA-99', 'NED BARONNE', 'Sports Bar', 'bottles', 5),
  ('SBA-737', 'NED MERLOT', 'Sports Bar', 'bottles', 5),
  ('SBA-1099', 'NED PINOTAGE', 'Sports Bar', 'bottles', 5),
  ('SBA-583', 'NEDERBERG DUET', 'Sports Bar', 'bottles', 5),
  ('SBA-730', 'NEDERBURG SHIRAZ', 'Sports Bar', 'bottles', 5),
  ('SBA-1644', 'NEETHLINGSHOF MALBEC', 'Sports Bar', 'bottles', 5),
  ('SBA-102', 'NEGERBURG CABERNET SAUV.', 'Sports Bar', 'bottles', 5),
  ('SBA-1143', 'NOBLE DRY RED', 'Sports Bar', 'bottles', 5),
  ('SBA-1144', 'NOBLE SWEET RED', 'Sports Bar', 'bottles', 5),
  ('SBA-1646', 'OLDENBURG CL', 'Sports Bar', 'bottles', 5),
  ('SBA-1640', 'PAINTED WOLF SHIRAZ', 'Sports Bar', 'bottles', 5),
  ('SBA-1611', 'PARMOUNT SYRAH', 'Sports Bar', 'bottles', 5),
  ('SBA-1638', 'PROTEA MERLOT', 'Sports Bar', 'bottles', 5),
  ('SBA-1639', 'REMHOOGTE MERLOT', 'Sports Bar', 'bottles', 5),
  ('SBA-1660', 'REMHOOGTE PINOTAGE', 'Sports Bar', 'bottles', 5),
  ('SBA-1637', 'SPIER MERLOT', 'Sports Bar', 'bottles', 5),
  ('SBA-1659', 'TOKARA CAB SAV', 'Sports Bar', 'bottles', 5),
  ('SBA-1612', 'ZONNEBLOEM CAB SAV', 'Sports Bar', 'bottles', 5),
  ('SBA-501', 'ZONNEBLOM MERLOT', 'Sports Bar', 'bottles', 5),
  ('SBA-651', 'ZONNEBLOM PINOTAGE', 'Sports Bar', 'bottles', 5),
  ('SBA-504', 'ZONNEBLOM SHIRAZ', 'Sports Bar', 'bottles', 5),
  ('SBA-59', 'BACARDI', 'Sports Bar', 'bottles', 5),
  ('SBA-56', 'CAPTAIN MORGAN BALCK', 'Sports Bar', 'bottles', 5),
  ('SBA-57', 'CAPTAIN MORGAN SPICED', 'Sports Bar', 'bottles', 5),
  ('SBA-972', 'CARIBBEAN WHITE RUM', 'Sports Bar', 'bottles', 5),
  ('SBA-971', 'HAVANA CLUB', 'Sports Bar', 'bottles', 5),
  ('SBA-60', 'MALAWI RUM', 'Sports Bar', 'bottles', 5),
  ('SBA-70', 'MARIBU', 'Sports Bar', 'bottles', 5),
  ('SBA-76', 'INFERNO LUPINI', 'Sports Bar', 'bottles', 5),
  ('SBA-78', 'JAGERMEISTER', 'Sports Bar', 'bottles', 5),
  ('SBA-79', 'OLMECA TEQUILA RED', 'Sports Bar', 'bottles', 5),
  ('SBA-75', 'OLMECA TEQUILA WHITE', 'Sports Bar', 'bottles', 5),
  ('SBA-74', 'ZAPPA', 'Sports Bar', 'bottles', 5),
  ('SBA-822', 'FOUR COUSIN- ROSE WINE', 'Sports Bar', 'bottles', 5),
  ('SBA-29', 'ABSOLUTE VODKA', 'Sports Bar', 'bottles', 5),
  ('SBA-1569', 'C ROCK VODKA', 'Sports Bar', 'bottles', 5),
  ('SBA-1723', 'CRUZ VODKA', 'Sports Bar', 'bottles', 5),
  ('SBA-1568', 'GREY GOOSE VODKA', 'Sports Bar', 'bottles', 5),
  ('SBA-30', 'MAINSTAY', 'Sports Bar', 'bottles', 5),
  ('SBA-27', 'MALAWI VODKA', 'Sports Bar', 'bottles', 5),
  ('SBA-1570', 'SKY VODKA', 'Sports Bar', 'bottles', 5),
  ('SBA-28', 'SMIRNOFF VODKA', 'Sports Bar', 'bottles', 5),
  ('SBA-967', 'BALLENTIES', 'Sports Bar', 'bottles', 5),
  ('SBA-986', 'BALLENTIES 12 YEARS', 'Sports Bar', 'bottles', 5),
  ('SBA-33', 'BELLS', 'Sports Bar', 'bottles', 5),
  ('SBA-31', 'BLACK LABEL', 'Sports Bar', 'crates', 8),
  ('SBA-1740', 'BLENDERS PRIDE', 'Sports Bar', 'bottles', 5),
  ('SBA-987', 'CHINEESE WHISKY', 'Sports Bar', 'bottles', 5),
  ('SBA-1667', 'CHINESE WHISKY BOTTLE', 'Sports Bar', 'bottles', 5),
  ('SBA-32', 'CHIVAS REGAL', 'Sports Bar', 'bottles', 5),
  ('SBA-816', 'DOUBLE BLACK LABLE', 'Sports Bar', 'bottles', 5),
  ('SBA-954', 'FAMOUSE GROUSE', 'Sports Bar', 'bottles', 5),
  ('SBA-1297', 'GLENFARCLAS', 'Sports Bar', 'bottles', 5),
  ('SBA-1441', 'GLENFIDDICH 15 YEARS', 'Sports Bar', 'bottles', 5),
  ('SBA-1462', 'GLENFIDDICH 18 YEARS', 'Sports Bar', 'bottles', 5),
  ('SBA-34', 'GLENFIDDISH 12 YEARS', 'Sports Bar', 'bottles', 5),
  ('SBA-988', 'GLENGARIOCH', 'Sports Bar', 'bottles', 5),
  ('SBA-1566', 'GLENLIVET 12YRS', 'Sports Bar', 'bottles', 5),
  ('SBA-1567', 'GLENLIVET FOUNDERS', 'Sports Bar', 'bottles', 5),
  ('SBA-950', 'GLENMORANGIE', 'Sports Bar', 'bottles', 5),
  ('SBA-1737', 'GLENMORANGIE 14 YRS', 'Sports Bar', 'bottles', 5),
  ('SBA-1738', 'GLENMORANGIE 16 YRS', 'Sports Bar', 'bottles', 5),
  ('SBA-965', 'GLENROTHERS', 'Sports Bar', 'bottles', 5),
  ('SBA-1190', 'GOLD LABEL JOHNIW WALKER', 'Sports Bar', 'bottles', 5),
  ('SBA-815', 'GRANTS', 'Sports Bar', 'bottles', 5),
  ('SBA-1565', 'GREEN LABEL', 'Sports Bar', 'crates', 8),
  ('SBA-990', 'GUIZHOU MOUNTAIN ZHEN', 'Sports Bar', 'bottles', 5),
  ('SBA-35', 'J & B', 'Sports Bar', 'bottles', 5),
  ('SBA-724', 'JACK DANIEL HONEY', 'Sports Bar', 'bottles', 5),
  ('SBA-1027', 'JACK DANIELS', 'Sports Bar', 'bottles', 5),
  ('SBA-1461', 'JAMESON', 'Sports Bar', 'bottles', 5),
  ('SBA-1271', 'JAMESON - SELECT RESERVE', 'Sports Bar', 'bottles', 5),
  ('SBA-1005', 'JIM BEAM', 'Sports Bar', 'bottles', 5),
  ('SBA-982', 'JOHNEEWALKER ADVENTURE', 'Sports Bar', 'bottles', 5),
  ('SBA-991', 'KWEICHOW MOUTAI', 'Sports Bar', 'bottles', 5),
  ('SBA-1575', 'MACALLAN 12 YEARS', 'Sports Bar', 'bottles', 5),
  ('SBA-1739', 'MONKEY SHOULDER', 'Sports Bar', 'bottles', 5),
  ('SBA-958', 'PASSPORT- SCOTCH', 'Sports Bar', 'bottles', 5),
  ('SBA-985', 'RAGGANMORE 12 YEARS', 'Sports Bar', 'bottles', 5),
  ('SBA-36', 'RED LABEL', 'Sports Bar', 'bottles', 5),
  ('SBA-1724', 'SINGLETONE WHISKY', 'Sports Bar', 'bottles', 5),
  ('SBA-72', 'SOUTHERN COMFORT', 'Sports Bar', 'bottles', 5),
  ('SBA-964', 'WOODFORD RESERVE', 'Sports Bar', 'bottles', 5),
  ('SBA-1655', 'BEUMONT CHENIN BLANK', 'Sports Bar', 'bottles', 5),
  ('SBA-1035', 'BOSCHANDAL-CHARDONAY', 'Sports Bar', 'bottles', 5),
  ('SBA-1105', 'BOSCHANDAL-SAVUGNON BLANC', 'Sports Bar', 'bottles', 5),
  ('SBA-1661', 'CAPE OF GOOD HOPE', 'Sports Bar', 'bottles', 5),
  ('SBA-1656', 'CEBERBERG GHOST CORNER SEMILLION', 'Sports Bar', 'crates', 8),
  ('SBA-1140', 'CHIANTI', 'Sports Bar', 'bottles', 5),
  ('SBA-1110', 'FLEUR DU CAP-CHARDONAY', 'Sports Bar', 'bottles', 5),
  ('SBA-1103', 'FLEUR DU CAP-SAVUGNON BLANC', 'Sports Bar', 'bottles', 5),
  ('SBA-775', 'FOUR COUSIN - SWEET WHITE WINE', 'Sports Bar', 'bottles', 5),
  ('SBA-1651', 'HARTENBERG CHARDONNAY', 'Sports Bar', 'bottles', 5),
  ('SBA-1650', 'KEN FORRESTER CHARDONNAY', 'Sports Bar', 'bottles', 5),
  ('SBA-1654', 'KEN FORRESTER CHENIN BLANC', 'Sports Bar', 'bottles', 5),
  ('SBA-1653', 'KEN FORRESTER SAV BLANC', 'Sports Bar', 'bottles', 5),
  ('SBA-91', 'NED LYRIC', 'Sports Bar', 'bottles', 5),
  ('SBA-93', 'NED SAUV. BLANC', 'Sports Bar', 'bottles', 5),
  ('SBA-682', 'NEDBERG RIESLING', 'Sports Bar', 'bottles', 5),
  ('SBA-511', 'NEDER STEINS', 'Sports Bar', 'bottles', 5),
  ('SBA-913', 'NEDERBURG - CHARDONAY', 'Sports Bar', 'bottles', 5),
  ('SBA-1145', 'NOBLE DRY WHITE', 'Sports Bar', 'bottles', 5),
  ('SBA-1146', 'NOBLE SWEET WHITE', 'Sports Bar', 'bottles', 5),
  ('SBA-1042', 'PINOT GRIGIO', 'Sports Bar', 'bottles', 5),
  ('SBA-1141', 'PROSECCO', 'Sports Bar', 'bottles', 5),
  ('SBA-1649', 'SPIER CHARDONNAY', 'Sports Bar', 'bottles', 5),
  ('SBA-1728', 'SPIER ROSE', 'Sports Bar', 'bottles', 5),
  ('SBA-1652', 'SPIER SAV BLANK', 'Sports Bar', 'bottles', 5),
  ('SBA-1004', 'ZONNEBLOM CHARDONAY', 'Sports Bar', 'bottles', 5),
  ('SBA-634', 'ZONNEBLOMBLOEM SAUVIGNO BLANC', 'Sports Bar', 'bottles', 5);

-- Expected: 559 rows in stock_items

-- ============================================================
-- STEP 3 — Opening balance movements (requires migration 030)
-- ============================================================
--
-- 533 rows. The 26 items that open at zero get no movement row —
-- a zero balance needs no ledger entry. STEP 4 still gives them a
-- current_stock row so they render as out-of-stock rather than vanishing.

INSERT INTO stock_movements (stock_item_id, movement_type, quantity_change, notes)
SELECT si.id, 'opening_balance', mapping.qty,
       'Initial catalogue import — demo quantity pending real stocktake'
FROM (VALUES
  ('RBA-980', 30),
  ('RBA-976', 15),
  ('RBA-978', 10),
  ('RBA-41', 4),
  ('RBA-1571', 20),
  ('RBA-43', 30),
  ('RBA-44', 18),
  ('RBA-989', 30),
  ('RBA-1422', 1),
  ('RBA-1722', 24),
  ('RBA-1197', 11),
  ('RBA-1196', 28),
  ('RBA-1112', 11),
  ('RBA-1195', 15),
  ('RBA-1420', 28),
  ('RBA-1421', 37),
  ('RBA-649', 5),
  ('RBA-108', 1),
  ('RBA-107', 27),
  ('RBA-561', 43),
  ('RBA-1710', 10),
  ('RBA-1001', 5),
  ('RBA-1695', 19),
  ('RBA-1006', 14),
  ('RBA-804', 15),
  ('RBA-656', 25),
  ('RBA-1291', 60),
  ('RBA-54', 32),
  ('RBA-86', 58),
  ('RBA-805', 10),
  ('RBA-1264', 25),
  ('RBA-751', 16),
  ('RBA-47', 15),
  ('RBA-1351', 1),
  ('RBA-81', 52),
  ('RBA-82', 16),
  ('RBA-1713', 20),
  ('RBA-53', 33),
  ('RBA-1711', 4),
  ('RBA-80', 14),
  ('RBA-1712', 54),
  ('RBA-84', 19),
  ('RBA-83', 36),
  ('RBA-806', 12),
  ('RBA-752', 14),
  ('RBA-1032', 23),
  ('RBA-567', 27),
  ('RBA-1718', 51),
  ('RBA-495', 32),
  ('RBA-1551', 36),
  ('RBA-112', 4),
  ('RBA-113', 38),
  ('RBA-111', 33),
  ('RBA-1318', 5),
  ('RBA-1319', 16),
  ('RBA-45', 10),
  ('RBA-1314', 32),
  ('RBA-46', 8),
  ('RBA-1725', 30),
  ('RBA-519', 6),
  ('RBA-733', 15),
  ('RBA-1317', 17),
  ('RBA-425', 15),
  ('RBA-665', 27),
  ('RBA-426', 27),
  ('RBA-520', 11),
  ('RBA-423', 22),
  ('RBA-1024', 15),
  ('RBA-497', 32),
  ('RBA-1016', 34),
  ('RBA-424', 23),
  ('RBA-1022', 3),
  ('RBA-979', 24),
  ('RBA-664', 21),
  ('RBA-963', 31),
  ('RBA-514', 6),
  ('RBA-973', 17),
  ('RBA-1185', 9),
  ('RBA-1159', 13),
  ('RBA-1322', 1),
  ('RBA-67', 2),
  ('RBA-961', 8),
  ('RBA-65', 4),
  ('RBA-1610', 2),
  ('RBA-970', 3),
  ('RBA-969', 23),
  ('RBA-957', 13),
  ('RBA-64', 15),
  ('RBA-977', 29),
  ('RBA-966', 4),
  ('RBA-63', 30),
  ('RBA-68', 14),
  ('RBA-1662', 5),
  ('RBA-611', 13),
  ('RBA-959', 37),
  ('RBA-968', 2),
  ('RBA-975', 8),
  ('RBA-1168', 57),
  ('RBA-11', 11),
  ('RBA-1469', 5),
  ('RBA-1698', 28),
  ('RBA-1709', 7),
  ('RBA-1454', 11),
  ('RBA-1109', 58),
  ('RBA-1714', 10),
  ('RBA-1697', 17),
  ('RBA-1706', 35),
  ('RBA-1720', 47),
  ('RBA-1699', 17),
  ('RBA-1731', 5),
  ('RBA-3', 2),
  ('RBA-1432', 23),
  ('RBA-1433', 24),
  ('RBA-19', 15),
  ('RBA-13', 7),
  ('RBA-370', 17),
  ('RBA-608', 41),
  ('RBA-1425', 51),
  ('RBA-7', 18),
  ('RBA-494', 43),
  ('RBA-1726', 7),
  ('RBA-280', 41),
  ('RBA-1009', 10),
  ('RBA-1025', 16),
  ('RBA-722', 4),
  ('RBA-18', 9),
  ('RBA-937', 8),
  ('RBA-20', 23),
  ('RBA-1029', 19),
  ('RBA-23', 30),
  ('RBA-25', 5),
  ('RBA-1217', 3),
  ('RBA-1097', 10),
  ('RBA-1460', 48),
  ('RBA-434', 7),
  ('RBA-17', 29),
  ('RBA-1044', 16),
  ('RBA-1648', 58),
  ('RBA-1293', 9),
  ('RBA-1355', 3),
  ('RBA-1142', 14),
  ('RBA-1627', 2),
  ('RBA-823', 21),
  ('RBA-544', 30),
  ('RBA-1220', 32),
  ('RBA-1147', 15),
  ('RBA-1447', 10),
  ('RBA-1647', 1),
  ('RBA-1658', 12),
  ('RBA-1642', 28),
  ('RBA-1289', 26),
  ('RBA-1104', 27),
  ('RBA-1108', 26),
  ('RBA-1643', 8),
  ('RBA-1613', 33),
  ('RBA-1437', 28),
  ('RBA-1636', 32),
  ('RBA-1354', 23),
  ('RBA-1106', 2),
  ('RBA-1170', 1),
  ('RBA-1427', 4),
  ('RBA-1635', 10),
  ('RBA-1729', 28),
  ('RBA-1641', 2),
  ('RBA-1645', 13),
  ('RBA-99', 10),
  ('RBA-737', 11),
  ('RBA-1099', 2),
  ('RBA-583', 31),
  ('RBA-1644', 8),
  ('RBA-102', 38),
  ('RBA-1143', 10),
  ('RBA-1144', 25),
  ('RBA-1646', 13),
  ('RBA-1640', 39),
  ('RBA-1611', 16),
  ('RBA-1638', 5),
  ('RBA-1639', 10),
  ('RBA-1660', 34),
  ('RBA-1637', 12),
  ('RBA-1659', 12),
  ('RBA-1612', 3),
  ('RBA-501', 15),
  ('RBA-651', 6),
  ('RBA-504', 21),
  ('RBA-59', 5),
  ('RBA-56', 3),
  ('RBA-57', 34),
  ('RBA-972', 6),
  ('RBA-971', 18),
  ('RBA-60', 18),
  ('RBA-70', 27),
  ('RBA-76', 13),
  ('RBA-78', 3),
  ('RBA-79', 28),
  ('RBA-75', 35),
  ('RBA-74', 33),
  ('RBA-822', 13),
  ('RBA-29', 11),
  ('RBA-1569', 3),
  ('RBA-1723', 8),
  ('RBA-1568', 21),
  ('RBA-30', 4),
  ('RBA-27', 34),
  ('RBA-1570', 40),
  ('RBA-28', 1),
  ('RBA-986', 8),
  ('RBA-33', 20),
  ('RBA-31', 35),
  ('RBA-987', 24),
  ('RBA-1667', 17),
  ('RBA-32', 28),
  ('RBA-816', 33),
  ('RBA-954', 38),
  ('RBA-1297', 1),
  ('RBA-1441', 1),
  ('RBA-1462', 11),
  ('RBA-34', 34),
  ('RBA-988', 40),
  ('RBA-1566', 22),
  ('RBA-1567', 1),
  ('RBA-950', 32),
  ('RBA-965', 6),
  ('RBA-1190', 12),
  ('RBA-1565', 11),
  ('RBA-990', 27),
  ('RBA-35', 33),
  ('RBA-1027', 22),
  ('RBA-1461', 39),
  ('RBA-1271', 3),
  ('RBA-1005', 36),
  ('RBA-982', 1),
  ('RBA-991', 8),
  ('RBA-1575', 9),
  ('RBA-958', 36),
  ('RBA-985', 26),
  ('RBA-36', 3),
  ('RBA-1724', 15),
  ('RBA-72', 23),
  ('RBA-964', 12),
  ('RBA-1655', 7),
  ('RBA-1035', 25),
  ('RBA-1661', 17),
  ('RBA-1656', 18),
  ('RBA-1140', 19),
  ('RBA-1110', 15),
  ('RBA-1103', 6),
  ('RBA-775', 7),
  ('RBA-1651', 16),
  ('RBA-1650', 13),
  ('RBA-1654', 4),
  ('RBA-1653', 27),
  ('RBA-91', 24),
  ('RBA-93', 16),
  ('RBA-511', 13),
  ('RBA-913', 9),
  ('RBA-1145', 20),
  ('RBA-1146', 2),
  ('RBA-1042', 10),
  ('RBA-1141', 14),
  ('RBA-1728', 16),
  ('RBA-1652', 22),
  ('RBA-1004', 7),
  ('RBA-634', 21),
  ('SBA-980', 10),
  ('SBA-976', 30),
  ('SBA-978', 31),
  ('SBA-41', 37),
  ('SBA-1571', 3),
  ('SBA-43', 12),
  ('SBA-44', 15),
  ('SBA-989', 3),
  ('SBA-1422', 18),
  ('SBA-981', 8),
  ('SBA-1722', 27),
  ('SBA-1197', 39),
  ('SBA-1196', 11),
  ('SBA-1112', 28),
  ('SBA-1195', 39),
  ('SBA-1420', 9),
  ('SBA-649', 12),
  ('SBA-108', 39),
  ('SBA-107', 5),
  ('SBA-561', 56),
  ('SBA-1710', 15),
  ('SBA-1001', 17),
  ('SBA-1695', 28),
  ('SBA-1006', 9),
  ('SBA-804', 27),
  ('SBA-1291', 14),
  ('SBA-54', 3),
  ('SBA-86', 7),
  ('SBA-805', 41),
  ('SBA-1264', 11),
  ('SBA-751', 24),
  ('SBA-47', 28),
  ('SBA-1351', 33),
  ('SBA-81', 41),
  ('SBA-82', 1),
  ('SBA-1713', 58),
  ('SBA-53', 12),
  ('SBA-1711', 1),
  ('SBA-80', 31),
  ('SBA-1712', 42),
  ('SBA-84', 31),
  ('SBA-83', 25),
  ('SBA-806', 46),
  ('SBA-752', 35),
  ('SBA-1032', 24),
  ('SBA-567', 57),
  ('SBA-1718', 12),
  ('SBA-495', 17),
  ('SBA-1551', 4),
  ('SBA-112', 25),
  ('SBA-113', 5),
  ('SBA-111', 25),
  ('SBA-1318', 13),
  ('SBA-1743', 2),
  ('SBA-1319', 40),
  ('SBA-45', 16),
  ('SBA-1314', 39),
  ('SBA-1742', 31),
  ('SBA-1725', 3),
  ('SBA-519', 22),
  ('SBA-733', 1),
  ('SBA-1317', 10),
  ('SBA-665', 29),
  ('SBA-426', 34),
  ('SBA-520', 3),
  ('SBA-423', 24),
  ('SBA-1024', 37),
  ('SBA-1016', 4),
  ('SBA-424', 34),
  ('SBA-1022', 39),
  ('SBA-979', 1),
  ('SBA-1741', 15),
  ('SBA-664', 9),
  ('SBA-963', 5),
  ('SBA-514', 31),
  ('SBA-973', 14),
  ('SBA-1159', 11),
  ('SBA-1322', 2),
  ('SBA-67', 8),
  ('SBA-961', 12),
  ('SBA-65', 27),
  ('SBA-1610', 21),
  ('SBA-970', 5),
  ('SBA-969', 2),
  ('SBA-957', 15),
  ('SBA-64', 40),
  ('SBA-977', 13),
  ('SBA-513', 5),
  ('SBA-966', 13),
  ('SBA-63', 23),
  ('SBA-68', 39),
  ('SBA-1662', 25),
  ('SBA-611', 19),
  ('SBA-959', 20),
  ('SBA-968', 6),
  ('SBA-975', 6),
  ('SBA-1168', 54),
  ('SBA-11', 21),
  ('SBA-1469', 14),
  ('SBA-1698', 11),
  ('SBA-1454', 59),
  ('SBA-1109', 60),
  ('SBA-1714', 43),
  ('SBA-1697', 9),
  ('SBA-1706', 23),
  ('SBA-1720', 46),
  ('SBA-1699', 12),
  ('SBA-1700', 20),
  ('SBA-3', 11),
  ('SBA-1432', 38),
  ('SBA-1433', 2),
  ('SBA-19', 32),
  ('SBA-13', 27),
  ('SBA-370', 2),
  ('SBA-608', 11),
  ('SBA-1425', 3),
  ('SBA-7', 51),
  ('SBA-494', 12),
  ('SBA-1726', 47),
  ('SBA-280', 29),
  ('SBA-1009', 13),
  ('SBA-1025', 3),
  ('SBA-722', 28),
  ('SBA-18', 21),
  ('SBA-937', 29),
  ('SBA-20', 9),
  ('SBA-1029', 48),
  ('SBA-23', 15),
  ('SBA-25', 26),
  ('SBA-1217', 10),
  ('SBA-1097', 20),
  ('SBA-1460', 45),
  ('SBA-434', 10),
  ('SBA-17', 7),
  ('SBA-1044', 12),
  ('SBA-1648', 36),
  ('SBA-1355', 28),
  ('SBA-1142', 37),
  ('SBA-1627', 21),
  ('SBA-823', 26),
  ('SBA-544', 18),
  ('SBA-1220', 27),
  ('SBA-1147', 4),
  ('SBA-1447', 4),
  ('SBA-1657', 9),
  ('SBA-1647', 24),
  ('SBA-1658', 11),
  ('SBA-1642', 40),
  ('SBA-1289', 28),
  ('SBA-1104', 17),
  ('SBA-1108', 21),
  ('SBA-1643', 1),
  ('SBA-1613', 19),
  ('SBA-1437', 34),
  ('SBA-1636', 33),
  ('SBA-1354', 20),
  ('SBA-1107', 40),
  ('SBA-1106', 4),
  ('SBA-1170', 17),
  ('SBA-1427', 32),
  ('SBA-1635', 5),
  ('SBA-1729', 9),
  ('SBA-1641', 39),
  ('SBA-1645', 8),
  ('SBA-99', 18),
  ('SBA-737', 23),
  ('SBA-1099', 14),
  ('SBA-583', 14),
  ('SBA-730', 25),
  ('SBA-1644', 40),
  ('SBA-102', 37),
  ('SBA-1143', 12),
  ('SBA-1646', 15),
  ('SBA-1640', 7),
  ('SBA-1611', 24),
  ('SBA-1638', 12),
  ('SBA-1639', 3),
  ('SBA-1660', 17),
  ('SBA-1637', 5),
  ('SBA-1659', 15),
  ('SBA-1612', 20),
  ('SBA-501', 38),
  ('SBA-651', 37),
  ('SBA-504', 34),
  ('SBA-59', 20),
  ('SBA-56', 3),
  ('SBA-57', 4),
  ('SBA-972', 12),
  ('SBA-971', 9),
  ('SBA-60', 8),
  ('SBA-70', 25),
  ('SBA-76', 14),
  ('SBA-78', 7),
  ('SBA-79', 2),
  ('SBA-75', 29),
  ('SBA-74', 14),
  ('SBA-822', 14),
  ('SBA-29', 14),
  ('SBA-1569', 23),
  ('SBA-1723', 20),
  ('SBA-1568', 14),
  ('SBA-30', 11),
  ('SBA-27', 10),
  ('SBA-1570', 7),
  ('SBA-28', 3),
  ('SBA-967', 6),
  ('SBA-986', 22),
  ('SBA-33', 3),
  ('SBA-31', 5),
  ('SBA-1740', 25),
  ('SBA-987', 6),
  ('SBA-1667', 2),
  ('SBA-32', 35),
  ('SBA-816', 2),
  ('SBA-954', 27),
  ('SBA-1297', 2),
  ('SBA-1441', 13),
  ('SBA-1462', 5),
  ('SBA-34', 15),
  ('SBA-988', 36),
  ('SBA-1566', 15),
  ('SBA-1567', 16),
  ('SBA-950', 14),
  ('SBA-1737', 38),
  ('SBA-1738', 2),
  ('SBA-965', 24),
  ('SBA-1190', 13),
  ('SBA-815', 2),
  ('SBA-1565', 11),
  ('SBA-990', 7),
  ('SBA-35', 30),
  ('SBA-724', 31),
  ('SBA-1027', 15),
  ('SBA-1461', 39),
  ('SBA-1271', 7),
  ('SBA-1005', 24),
  ('SBA-982', 27),
  ('SBA-991', 29),
  ('SBA-1575', 39),
  ('SBA-1739', 8),
  ('SBA-958', 31),
  ('SBA-36', 22),
  ('SBA-1724', 35),
  ('SBA-72', 39),
  ('SBA-964', 9),
  ('SBA-1655', 20),
  ('SBA-1035', 8),
  ('SBA-1105', 28),
  ('SBA-1656', 43),
  ('SBA-1140', 7),
  ('SBA-1110', 35),
  ('SBA-1103', 33),
  ('SBA-775', 37),
  ('SBA-1651', 23),
  ('SBA-1650', 2),
  ('SBA-1654', 7),
  ('SBA-1653', 39),
  ('SBA-93', 36),
  ('SBA-682', 34),
  ('SBA-511', 4),
  ('SBA-913', 5),
  ('SBA-1145', 18),
  ('SBA-1146', 36),
  ('SBA-1042', 2),
  ('SBA-1141', 14),
  ('SBA-1649', 38),
  ('SBA-1728', 38),
  ('SBA-1652', 27),
  ('SBA-634', 36)
) AS mapping(sku, qty)
JOIN stock_items si ON si.sku = mapping.sku;

-- Expected: 533 rows in stock_movements

-- ============================================================
-- STEP 4 — Derive current_stock from the movement ledger
-- ============================================================
--
-- LEFT JOIN so every one of the 559 items gets a row, including the 26
-- with no movements (COALESCE -> 0). An item with no current_stock row
-- is INVISIBLE on Stock Levels — StockLevelsTab iterates current_stock
-- and joins stock_items, so a missing row drops the item from the screen
-- entirely rather than showing it at zero.
--
-- Deriving rather than re-listing quantities guarantees
-- current_stock.quantity = sum(stock_movements.quantity_change) per item.

INSERT INTO current_stock (stock_item_id, quantity)
SELECT si.id, COALESCE(SUM(sm.quantity_change), 0)
FROM stock_items si
LEFT JOIN stock_movements sm ON sm.stock_item_id = si.id
GROUP BY si.id;

-- Expected: 559 rows in current_stock

-- ============================================================
-- VERIFICATION — run BEFORE COMMIT
-- ============================================================

--   SELECT count(*) FROM stock_items;      -- expect 559
--   SELECT count(*) FROM stock_movements;  -- expect 533
--   SELECT count(*) FROM current_stock;    -- expect 559
--
--   SELECT department, count(*) FROM stock_items GROUP BY department;
--   -- expect: Restaurant Bar 276, Sports Bar 283
--
--   SELECT unit, count(*) FROM stock_items GROUP BY unit;
--   -- expect: bottles 475, crates 84
--
--   SELECT count(*) FILTER (WHERE cs.quantity = 0)                              AS out_of_stock,
--          count(*) FILTER (WHERE cs.quantity > 0 AND cs.quantity < si.reorder_level) AS below_reorder,
--          count(*) FILTER (WHERE cs.quantity >= si.reorder_level)              AS ok
--   FROM current_stock cs JOIN stock_items si ON si.id = cs.stock_item_id;
--   -- expect: 26 / 78 / 455
--
--   -- ledger and balances must agree for every item:
--   SELECT count(*) FROM current_stock cs
--   WHERE cs.quantity <> (
--     SELECT COALESCE(SUM(quantity_change), 0) FROM stock_movements sm
--     WHERE sm.stock_item_id = cs.stock_item_id);
--   -- expect: 0
--
--   -- spot-check:
--   SELECT si.sku, si.name, si.department, si.unit, si.reorder_level, cs.quantity
--   FROM stock_items si JOIN current_stock cs ON cs.stock_item_id = si.id
--   ORDER BY si.department, si.name LIMIT 20;

-- If every count matches, COMMIT. If not, ROLLBACK and diagnose.
COMMIT;
